# Generated by Django 4.0.3 on 2022-04-09 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('contents', models.TextField(blank=True)),
                ('matches', models.IntegerField(blank=True)),
                ('Scrape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.scrape')),
            ],
        ),
    ]
